linear_feedback_controller:
  ros__parameters:
    type: linear_feedback_controller/LinearFeedbackController
    chainable_controller:
      command_interfaces:
        - passthrough_controller/torso_lift_joint/effort
        - passthrough_controller/arm_1_joint/effort
        - passthrough_controller/arm_2_joint/effort
        - passthrough_controller/arm_3_joint/effort
        - passthrough_controller/arm_4_joint/effort
        - passthrough_controller/arm_5_joint/effort
        - passthrough_controller/arm_6_joint/effort
        - passthrough_controller/arm_7_joint/effort
    reference_prefix: linear_feedback_controller
    moving_joint_names:
      - torso_lift_joint
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
    torso_lift_joint:
      p: 50.0
      d: 0.5
    arm_1_joint:
      p: 50.0
      d: 0.5
    arm_2_joint:
      p: 50.0
      d: 0.5
    arm_3_joint:
      p: 50.0
      d: 0.5
    arm_4_joint:
      p: 50.0
      d: 0.5
    arm_5_joint:
      p: 10.0
      d: 0.3
    arm_6_joint:
      p: 5.0
      d: 0.3
    arm_7_joint:
      p: 5.0
      d: 0.3
    robot_has_free_flyer: false
    remove_gravity_compensation_effort: false
    joint_velocity_filter_coefficient: 0.9
    pd_to_lf_transition_duration: 0.5
