---
passthrough_controller:
  ros__parameters:
    type: linear_feedback_controller/PassthroughController
    command_interfaces: [
      wheel_left_joint/effort,
      wheel_right_joint/effort,
      # torso_lift_joint/effort,
      arm_1_joint/effort,
      arm_2_joint/effort,
      arm_3_joint/effort,
      arm_4_joint/effort,
      arm_5_joint/effort,
      arm_6_joint/effort,
      arm_7_joint/effort]
    reference_interfaces: [
      wheel_left_joint/effort,
      wheel_right_joint/effort,
      # torso_lift_joint/effort,
      arm_1_joint/effort,
      arm_2_joint/effort,
      arm_3_joint/effort,
      arm_4_joint/effort,
      arm_5_joint/effort,
      arm_6_joint/effort,
      arm_7_joint/effort
    ]
